spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/umc_week7_carrot
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true