spring:
  datasource:
    url: jdbc:mariadb://choeun-database-1.ccfgdtrf5skz.ap-northeast-2.rds.amazonaws.com:3306/carrot
    username: admin
    password: short0720
    driver-class-name: org.mariadb.jdbc.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true